proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: simple
  admin-groups: scientists
  users:
    - name: jack
      password: password
      groups: scientists
    - name: jeff
      password: password
      groups: mathematicians
  docker:
    url: http://localhost:2375
    port-range-start: 20000
  specs:
    - id: interactiveDisplay
      display-name: InteractiveDisplay
      description: package for enabling powerful shiny web displays of Bioconductor objects
      container-image: openanalytics/eurobioc2023-shinyproxy-interactive-display

logging:
  file:
    name: shinyproxy.log
